logFilters:
  - level: discard
    pattern: "esbuild-*@* * is incompatible with this module, link skipped."

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/plugin-envs.cjs
    spec: "https://raw.githubusercontent.com/Ayc0/yarn-plugin-envs/v0.0.3/src/index.js"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/plugin-dedupe-on-install.cjs
    spec: "https://raw.githubusercontent.com/ambar/yarn-plugin-dedupe-on-install/main/index.js"

yarnPath: .yarn/releases/yarn-3.0.2.cjs
